### PR TITLE
Add App.init_settings method

### LINKED ISSUE #430: settings_sections directive
There's the use case where the developer wants to read settings from a file. Currently you could use ``setting`` or ``setting_section`` to parse a file and introduce settings. But what if you have multiple setting sections in a file? Reloading and reparsing the settings file isn't ideal.

We could introduce a ``setting_sections`` directive, better name perhaps ``load_setting_sections``, which lets you return multiple setting section dictionaries in a list. These get inserted into the settings object. They're overridable as before, as this is implemented using a composite action on top of ``setting_section``.

In ``inject_setting_sections`` you could inspect the command line args or environment to determine the settings file, and then load it and parse it into a list of setting section dictionaries. This gives the developer a canonical place to do this. We should document this as the regular pattern giving an example that uses configparser. Using this directive you can even develop a framework app base class that has some default behavior baked in.

### PR DESCRIPTION
**Pull request by henri-hulski**
Fix #430.

### CODE REVIEW

**Comment by faassen** [comment]
Looks good! Add a note to changes and to the part of the docs where we talk about settings and we're good to go.

**Comment by henri-hulski** [comment]
@faassen Just for curiosity, do you know, why the following doesn't work?
```python
    @classmethod
    def init_settings(cls, settings):
        for section, section_settings in settings.items():
            cls.setting_section(section)(lambda: section_settings)
```
It registers the section_settings of the last section for all sections.
Similar to
```python
        for section, section_settings in settings.items():
            for name, value in section_settings.items():
                cls.setting(section, name)(lambda: value)
```
which registers the last value for all names in all sections.

**Comment by henri-hulski** [comment]
Added tests for loading settings from JSON and YAML config files.

**Comment by faassen** [comment]
I'm not sure about the yaml tests. It's nice to know that they work but it pulls in a new dependency for the tests and I'm not sure what these tests add. It's good to have *example code* that looks like this, so I'd be more inclined to make this part of the documentation on settings and then you might need a dependency on pyyaml after all in the documentation tests.

**Comment by faassen** [comment]
So you're saying that the inline version registers only a single section, the last one that is given in the for loop? That is indeed mysterious. It's as if things get silently overridden, which is also weird as you'd expect a conflict. A directive action shouldn't just randomly override a previous one, it should execute it separately. What happens if you put a print in the ``perform`` of the setting action?

**Comment by henri-hulski** [comment]
It register all sections, but sets the settings for the last section for all sections. 
In the second example it register all sections and settings, but the values for all settings are set to the last value of the loop.

**Comment by henri-hulski** [comment]
@faassen 
When adding to `actions` in `SettingSectionAction`
```python
        print(self.section)
        print(section)
```
and using in `app`
```python
    for section, section_settings in settings.items():
        cls.setting_section(section)(lambda: section_settings)
```
for the first test I get
```
foo
{'security': False, 'space': 'huge'}
bar
{'security': False, 'space': 'huge'}
```
for `test_loading_settings_from_file()` I get
```
transaction
{'debug': True}
jwtauth
{'debug': True}
sqlalchemy
{'debug': True}
jinja2
{'debug': True}
chameleon
{'debug': True}
```

**Comment by henri-hulski** [comment]
Added documentation to settings.rst, updated CHANGES.txt and removed the YAML test.

@taschini 
Actually not really sure how to integrate doctests here.
If you've time please take a look and give me a hint.

**Comment by taschini** [comment]
@henri-hulski , you can have a look at ``doc/quickstart.rst``, which has some example of code testing. You can mark code to be executed as follows:

```
You can load it with:

  .. testcode::

  import yaml

  config = open('settings.yml')
  settings_dict = yaml.load(config)

```

**NB**: You must not use double-colon (::) in the text that introduces the code fragment.

Then you can show that the app has in fact received the settings as follows::

```
Now register the settings dictionary in the App settings
before starting the App:

  .. testcode::

  App.init_settings(settings_dict)
  morepath.commit(App)

You can access the settings as before:

   >>> app.settings.jwtauth.algorithm
   'ES256'

```

Note again the absence of the double colon (::) from the introductory text.

**Comment by taschini** [comment]
I was looking at ``test_loading_settings_from_json`` and I am really not sure about what it is supposed to test.  You already have tested ``App.init_settings`` quite extensively before, and I don't see what the value of the fact that its argument has been loaded from a JSON file is.  As for the YAML test discussed by @faassen before, I think it's good to have it as an example, but not necessarily as part of the test-suite.

**Comment by taschini** [comment]
BTW, I think that the recommended way to load YAML data from file is

```
  with open('settings.yml') as config:
       settings_dict = yaml.load(config)


```

**Comment by faassen** [comment]
I was going to do one of those cool github +1 things to @taschini's comment about JSON testing but my mobile github app doesn't let me do it, I think.

Good idea to put example code in the docs instead.

**Comment by henri-hulski** [comment]
The json and yaml test I mainly wrote for preparing the docs, so I'm sure everything works in Python 2 and 3. And actually found some problems with PY3.
So now I can move them to the tests.

**Comment by henri-hulski** [comment]
@taschini Do you have an idea how to make doctest finding 'settings.yml'?

**Comment by taschini** [comment]
AFAIK Sphinx runs within the ``doc/`` directory so either you put that file in there or you specify the directory when you load it:

```
with open('path/settings.yml') as config:
```

In case of doubt, just run Sphinx once with a fake test to tell you the current directory:

```
>>> import os; os.getcwd()
```

**Comment by henri-hulski** [comment]
I've added the doctests for YAML.

Using os.chdir for change to the code_examples directory.
But it seems not to work with travis, so I will fix that.

I was not able to setup the json test as json.load produces in Python 2.7 unicode, 
while yaml.load produces strings. And in Python 3 I think there will also be strings for json.load.

Py.test doctest integration has introduced a `ALLOW_UNICODE` flag to strip the u prefix, but sphinx doctest doesn't support such a flag.

**Comment by taschini** [comment]
@henri-hulski, a few remarks:

* the safe way to get a reference to the ``code_examples`` directory is as follows:

  ```
      import hello, os
      os.path.dirname(hello.__file__)
  ```

* Be aware that running the doc tests as described in ``doc/developing.rst`` will fail, as the ``pyyaml`` is missing from buildout.

**Comment by taschini** [comment]
@henri-hulski, You looked like you were struggling a bit with that, so I took the liberty of fixing the reference to the ``code_examples`` directory. I hope you don't mind.

**Comment by henri-hulski** [comment]
@taschini 
Actually fixed it myself with
```python
  os.chdir(os.path.join(os.path.dirname(os.path.abspath(morepath.__file__)),
                        '../doc/code_examples'))
```
This seems to me cleaner, as `hello` is not really related here.
On the other hand your way is shorter.

About dependency, I moved pyyaml from tox.ini to the test section in setup.py.

Where I really need help is with the JSON test as I have no idea how to resolve the problem I described above.

**Comment by taschini** [comment]
I thinks that it's the YAML part that needs fixing, not the JSON part: they should be unicode strings.

I think that the following should work:

```
 yaml.add_constructor(u'tag:yaml.org,2002:str', lambda loader, node: loader.construct_scalar(node))
```

**Comment by henri-hulski** [comment]
Actually Pytest was passing for both, JSON and YAML in PY2.7 and PY3.
Doctests did not. Does that mean, that Pytest is more tolerant?

@taschini Don't really know where to put that fix. I think it should be hidden, as in real world you will not use it.

**Comment by taschini** [comment]
> @taschini Don't really know where to put that fix. I think it should be hidden, as in real world you will not use it.

I wouldn't be so sure about that. Anyway, I would put it after you import ``yaml`` and before you read the file:

```
  import yaml
  
  # Ensure that PyYAML always constructs unicode strings:
  yaml.add_constructor(
      u'tag:yaml.org,2002:str',
      lambda loader, node: loader.construct_scalar(node))

  with open('settings.yml') as config:
       settings_dict = yaml.load(config)

```

**Comment by henri-hulski** [comment]
@taschini Yeah, that seems to work in Python 2.
I added also doctests for Python 3.4, but here are failing now both as they now produce strings.
This I actually expected.

> @taschini Don't really know where to put that fix. I think it should be hidden, as in real world you will not use it.

>I wouldn't be so sure about that.

@href You have experience with YAML. What do you think?

**Comment by href** [comment]
I'm no longer using Python 2, so I don't get those Unicode problems ;)

I think we should just fix the tests and not mention the unicode workaround. This is not our problem and if we mention a workaround we have to keep it up to date (maybe in the future the workaround changes).

So I would simply change the tests from `assert 'x' == u'x'` to `assert 'x' == 'x'`. Our example should depend on default settings. Anything else falls outside the scope of this documentation imho.

Config files are somewhat more likely to not go beyond ASCII anyway.

**Comment by henri-hulski** [comment]
@href This is, what I had before, but then the tests fail for json under Python 2 (see above).
So we have to fix JSON for Python 2. This is also my preferred solution, but I don't know how.

**Comment by href** [comment]
I think I'd basically just keep this out of this PR for now then. The init_settings feature is great either way.

**Comment by henri-hulski** [comment]
So just revert to leave out the tests for JSON. 
Actually with Pytest all tests were passing.

**Comment by taschini** [comment]
I think that this pull request is drifting a bit off its focus:

* Running the doc tests with Python 3 is something that affects quite a few other places and should probably done in a separate pull request.

* If you have to chose between testing the YAML and the JSON config settings, I think it would make more sense to test the JSON one. In this way you don't need to introduce any additional dependency.

**Comment by henri-hulski** [comment]
I prefer testing YAML for two reasons. First we decided to make it our first class config and second it behaves the same in PY2 and PY3 so the doctests pass in both. 

I will extract the PY3 doctests to a separate PR.

**Comment by henri-hulski** [comment]
So I removed the JSON doctest, but left a shorter version of the JSON pytest, which tests, if the JSON file gets correctly loaded.
Also removed the Python 3.4 doctests. Will create a separate PR for them.

@faassen For me this PR can be merged.

**Comment by taschini** [comment]
I don't understand what ``test_loading_json`` in ``morepath/tests/test_init_settings.py`` is supposed to be testing. Is it testing that ``json.load`` works? That hardly belongs to our test suite. Is it testing that a different copy of the JSON file in the examples is syntactically correct JSON? That also hardly belongs to the test-suite.

If you have a concern that the JSON example file might be incorrect that should be doctested::

```
To load it use:

.. testcode:: json

  import json

  with open('settings.json') as config:
       settings_dict = json.load(config)
```

If you don't want the rest of the doctests to apply to the JSON code, you simply have to tell that it applies to yaml only:

```
You can access the settings as before:

.. doctest:: yaml

   >>> app.settings.jinja2.extensions
   ['jinja2.ext.autoescape', 'jinja2.ext.i18n']

   >>> app.settings.jwtauth.algorithm
   'ES256'

   >>> app.settings.sqlalchemy.url
   'sqlite:///morepath.db'

```
Ultimately, the purpose of the test-suite in ``morepath.test`` is to verify that Morepath works as expected, whereas the purpose of doctesting is to verify that the examples in the docs are correct.

If the object of your testing is an example used in the docs, it does not belong to the ``morepath.test``.

**Comment by taschini** [comment]
You have to specify the yaml also here:

```
Now register the settings dictionary in the App settings
before starting the App:

.. testcode:: yaml

  App.init_settings(settings_dict)
  morepath.commit(App)

  app = App()


```

**Comment by henri-hulski** [comment]
Yeah, that is strange.
In the [docs](http://www.sphinx-doc.org/en/stable/ext/doctest.html) we have:

> If it is *, the block is assigned to all groups

**Comment by taschini** [comment]
I was looking to ``test_loading_settings_from_file`` in ``morepath/tests/test_init_settings.py``.

Despite the name, the settings are not coming from a file, they are just defined in a different module. Does it test anything that has not already been tested before? 

The actual contents of the settings are the same as the example in the docs, and they get tested there.

**Comment by taschini** [comment]
In the conversation that we had on the 27th of May on Discord (around 12:14), we talked about introducing a new extension, ``more.yamlconfig``, to handle configurations based on YAML files. The purpose of this PR should be simply to have the imperative API for initializing settings in place, which was basically achieved with the first commit on this branch.

In light of that discussion, I do think that ``more.yamlconfig`` might be a better place to host ``test_extentions_settings`` (and the related fixture package) than ``morepath/tests/test_init_settings.py``.

@henri-hulski, If you feel that the ``more.yamlconfig`` extension is not needed and that you would like to have that capability straight in ``morepath`` that should be discussed in a separate topic on the issue tracker.

Having said that, this PR is now passing all the tests, App.init_settings does what it was supposed to do, and if @faassen wants to merge it (perhaps with *squashing*), I have no major objection.

**Pull request merged**
