### PR TITLE
Clean requirements

### PR DESCRIPTION
**Pull request by henri-hulski**

### CODE REVIEW

**Comment by henri-hulski** [comment]
Clean up the requirements to make them more DRY and maintainable.

**Comment by henri-hulski** [comment]
@faassen  I get an error, when running tox locally, that directive from Dectate cannot be imported. 

Try here to install the libraries explicitly from src/, but it doesn't help.

**Comment by henri-hulski** [comment]
Yeah tox still install the released versions of reg etc. with pip.
Try to find out how to tell tox to install the local versions (see tox.ini and requirements/src.txt in this PR).
But no success for now.

**Comment by henri-hulski** [comment]
Seems to be a bug in pip which don't allow declaring project names on relative paths for editable directories with the `#eggs=project_name` syntax.
See pypa/pip#328.

I have worked out a work-around by specifying absolute paths in tox.ini using the `{toxinidir}` variable.

**Comment by henri-hulski** [comment]
@faassen Could you take a look at this and tell me also if you still need requirements/doc.txt (new location)?

**Comment by faassen** [comment]
So this splits up develop_requirements again? What does the new installation command look like? I was getting used to ``-Ur develop_requirements.txt``. I'm not sure whether documentation requirements are needed for readthedocs -- I experimented with them due to some build failures there but I later realized it's was because development versions of Reg didn't exist.

**Comment by henri-hulski** [comment]
Not so big change. Just `-Ur requirements/develop.txt`. Already fixed in the docs.
Just organized the requirements so that each should only be in one file.
Hope this makes maintenance easier.

**Comment by henri-hulski** [comment]
@faassen So I will remove the documentation requirements.

**Pull request merged**
