### PR TITLE
Use topological_sort from dectate (#403)

### LINKED ISSUE #403: reuse topological sort from Dectate
Officially publish it as part of the dectate API and use it. Same with the error. This should also
fix this issue brought up by @henri-hulski :

> is there a reason why you declare TopologicalSortError 2 times, in error.py and toposort.py?

### PR DESCRIPTION
**Pull request by taschini**
This closes #403.

### CODE REVIEW

**Comment by taschini** [comment]
Well, ``tox.ini`` picks dectate from pypi, if I correctly understand. So the builds by Travis will fail.
I'm not sure what's the best way to proceed:

1. Wait until the next release of dectate

    or

2.  Have tox pick dectate from source.

**Comment by faassen** [comment]
I think we just wait until the release of Dectate to merge this. I'd ideally like to sort out the autocommit story before then.

**Comment by taschini** [comment]
Agreed. I don't think this is urgent matter.

**Comment by faassen** [comment]
Thank you!

**Comment by taschini** [comment]
Well, that was quick!

**Pull request merged**
