### PR TITLE
Fix supported template in compared.rst

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by href** [comment]
Thanks! Actually we *do* have a [more.mako](https://github.com/morepath/more.mako) package, but  it's not been released on PyPI. So for now we should adopt your change. Thank you! Good catch.

@taschini Can we get a release for more.mako?

**Comment by faassen** [comment]
ping @blaflamme

**Comment by blaflamme** [comment]
@faassen you want me to release on pypi?

**Comment by blaflamme** [comment]
@faassen also Pyramid has a well supported mako bindings, don't know why it has been removed.

**Pull request merged**
